### ISSUE TITLE
Upgrade to algoliasearch 2.0

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-algolia#18]
I've been contacted by @nunomaduro to try the new algoliasearch 2.0.0b2 on this package.

Here is the gist of the new API usage: https://gist.github.com/nunomaduro/c59af518ef9d4ead937ba8310544d11c

**Comment by Natim** [comment]
The version 2.0 has been released which is now breaking the plugin.

**Comment by Natim** [comment]
Apparently there is a migration guide here: https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/python/

**Comment by nunomaduro** [comment]
To fix the current version, at the moment you can just fix the current dependencies adding:

`algoliasearch>=1.0,<2.0`

**Comment by Natim** [comment]
Yes that's what I did :) I am going to follow the upgrade guide, I'll keep you posted.
